module Babelish
  class XcodeMacros
    attr_accessor :content, :table, :keys
    def initialize(table = "Localizable", keys = {})
      @content = ""
      @table = table
      @keys = keys
    end

    def self.write_macros(file_path, table, keys)
      instance = XcodeMacros.new
      instance.process(table, keys)
      instance.write_content(file_path)
    end

    def process(table, keys)
      keys.each do |key|
        @content << String.new(<<-EOS)
#define #{key} NSLocalizedStringFromTable(@"#{key}",@"#{table}",@"")
        EOS
      end
      @content
    end

    def write_content(file_path)
      header = String.new(<<-EOS)
//
//  file_path
//  
//  This file was generated by Babelish
//  
//  https://github.com/netbe/babelish
//
        EOS
      header.gsub! "file_path", file_path
      file = File.new(file_path, "w")
      file.write header + @content
      file.close
    end
  end
end
