require "test_helper"
class TestXcodeMacros < Test::Unit::TestCase
  def test_process
    keys = ["LS_TITLE", "LS_BUTTON"]
    table = "Localizable"
    xcode_macros = Babelish::XcodeMacros.new
    content = xcode_macros.process(table, keys)
    expected_output = String.new(<<-EOS)
#define LS_TITLE NSLocalizedStringFromTable(@"LS_TITLE",@"Localizable",@"")
#define LS_BUTTON NSLocalizedStringFromTable(@"LS_BUTTON",@"Localizable",@"")
    EOS
    assert_equal expected_output, content
  end

  def test_write_macros
    keys = ["LS_TITLE", "LS_BUTTON"]
    table = "Localizable"
    Babelish::XcodeMacros.write_macros("Babelish.h", table, keys)
    expected_output = String.new(<<-EOS)
//
//  Babelish.h
//  
//  This file was generated by Babelish
//  
//  https://github.com/netbe/babelish
//
#define LS_TITLE NSLocalizedStringFromTable(@"LS_TITLE",@"Localizable",@"")
#define LS_BUTTON NSLocalizedStringFromTable(@"LS_BUTTON",@"Localizable",@"")
    EOS
    assert File.exists?("Babelish.h")
    result = File.read("Babelish.h")
    assert_equal expected_output, result
    #clean up
    system("rm -f ./Babelish.h")
  end
end
